# Generated by Django 6.0.6 on 2026-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_populate_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='symbol_image',
            field=models.CharField(blank=True, help_text='Static file path (e.g. symbols/surya.svg)', max_length=200),
        ),
    ]
